name: Deploy NF Scanner

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v7

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*

      - name: Instalar dependências
        run: npm install

      - name: Compilar aplicação
        run: npm run build -- --base=/nf-scanner/

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v6

      - name: Enviar arquivos do site
        uses: actions/upload-pages-artifact@v5
        with:
          path: './dist'

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
